### PR TITLE
Negative integers and precision indicators

### PR DESCRIPTION
**Pull request by psfblair**
Looks like erldn currently returns a symbol if you give it a negative integer or float, and also doesn't know how to handle the M and N precision indicators in edn. I've added some tests and fixes for these issues.

### CODE REVIEW

**Comment by marianoguerra** [comment]
thanks!

**Comment by marianoguerra** [comment]
new version on hex.pm https://hex.pm/packages/erldn/1.0.4

**Comment by psfblair** [comment]
Fantastic! Thanks so much!

**Comment by psfblair** [comment]
Something isn't working right with the 1.0.4 release on hex. If I go into my checked-out erldn project with the latest from GitHub on master, I get this:

    cat VERSION 
    1.0.4
    rebar compile
    erl -pa ebin
    1> erldn:lex_str("-1").
    {ok,[{integer,1,-1}],1}

but if I go to the dependency as downloaded from hex, e.g., in my exdn project directory, I get this:

    cd exdn/deps/erldn
    cat VERSION 
    1.0.4
    erl -pa ebin
    Eshell V7.2.1  (abort with ^G)
    1> erldn:lex_str("-1").  
    {ok,[{symbol,1,'-1'}],1}

Looks like maybe the changes to the erldn_lexer.xrl didn't get compiled in somehow? I see the new changes in exdn/deps/erldn/src but they don't seem to be working in the shell somehow.

**Comment by marianoguerra** [comment]
check 1.0.5 it seems hex publishes the generated .erl files for leex and yecc

I cleaned and compiled before publishing this one.

**Comment by psfblair** [comment]
Works now. Thanks!

**Comment by marianoguerra** [comment]
thank you!

**Pull request merged**
